name: Deploy Moleculer Api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies and Build Moleculer App
        run: |
          npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t samsoninho/moleculer_api .
          docker push samsoninho/moleculer_api

      - name: SSH into Ubuntu Server and Pull Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            docker pull samsoninho/moleculer_api

      - name: Run Docker Container on Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            docker stop moleculer_api || true
            docker rm moleculer_api || true
            docker run -d --name moleculer_api -p 3030:5000 samsoninho/moleculer_api
